<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Cangkiran', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bubakan', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangmalang', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Polaman', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Purwosari', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tambangan', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wonolopo', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mijen', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jatibarang', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kedungpane', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Ngadirgo', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wonoplumbon', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jatisari', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pesantren', 'Mijen']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gunungpati', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Plalangan', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pakintelan', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mangunsari', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Patemon', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Ngijo', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pongangan', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Nongkosawit', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Cepoko', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jatirejo', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sekaran', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sadeng', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sukorejo', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kandri', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kalisegoro', 'Gunungpati']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Randusari', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Barusari', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bulustalan', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mugassari', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pleburan', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wonodri', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Peterongan', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Lamper Lor', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Lamper Kidul', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Lamper Tengah', 'Semarang Selatan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pudakpayung', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gedawang', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jabungan', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Padangsari', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Banyumanik', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Srondol Wetan', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pedalangan', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sumurboto', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Srondol Kulon', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tinjomoyo', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Ngesrep', 'Banyumanik']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sampangan', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bendan Duwur', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangrejo', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gajahmungkur', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bendan Ngisor', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Petompon', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bendungan', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Lempongsari', 'Gajahmungkur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sembungharjo', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kudu', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangroto', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Banjardowo', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gebangsari', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Genuksari', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Trimulyo', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Penggaron Lor', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Muktiharjo Lor', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bangetayu Kulon', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bangetayu Wetan', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Terboyo Wetan', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Terboyo Kulon', 'Genuk']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gemah', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pedurungan Kidul', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Plamongansari', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Penggaron kidul', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pedurungan Lor', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tlogomulyo', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pedurungan Tengah', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Palebon', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kalicari', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tlogosari Kulon', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tlogosari Wetan', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Muktiharjo Kidul', 'Pedurungan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pandean Lamper', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gayamsari', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Siwalan', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sambirejo', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sawah Besar', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kaligawe', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tambakrejo', 'Gayamsari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangturi', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangtempel', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Rejosari', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sarirejo', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kebonagung', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bugangan', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mlatiharjo', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mlatibaru', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Rejomulyo', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kemijen', 'Semarang Timur']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jatingaleh', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karanganyar Gunung', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jomblang', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Candi', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kaliwiru', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wonotingal', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tegalsari', 'Candisari']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Rowosari', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Meteseh', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kramas', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tembalang', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bulusan', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mangunharjo', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sendangmulyo', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sambiroto', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jangli', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tandang', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kedungmundu', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sendangguwo', 'Tembalang']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bandarharjo', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tanjungmas', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bulu Lor', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Plombokan', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Purwosari', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Dadapsari', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kuningan', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Panggung Kidul', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Panggung Lor', 'Semarang Utara']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Miroto', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Brumbungan', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jagalan', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kranggan', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gabahan', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kembangsari', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sekayu', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pandansari', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bangunharjo', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kauman', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karang Kidul', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pekunden', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Purwodinatan', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pindrikan Kidul', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Pindrikan Lor', 'Semarang Tengah']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Ngemplak Simongan', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Manyaran', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Krapyak', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tambakharjo', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kalibanteng Kulon', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kalibanteng Kidul', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gisikdrono', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bongsari', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bojong Salaman', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Salaman Mloyo', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Cabean', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karangayu', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Krobokan', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tawangsari', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kembangarum', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tawang Mas', 'Semarang Barat']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Jerakah', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tugurejo', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Karanganyar', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Randugarut', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mangkang Wetan', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mangkang Kulon', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Mangunharjo', 'Tugu']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Podorejo', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wates', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Beringin', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Ngaliyan', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Bambankerep', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Kalipancur', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Purwoyoso', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Tambakaji', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Gondoriyo', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Wonosari', 'Ngaliyan']);
        DB::insert('insert into kelurahan (kelurahan, kecamatan) values (?, ?)', ['Sumurrejo', 'Ngaliyan']);
    }
}
